version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: adwise_backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_SECRET_KEY=production-secure-fallback-key-change-me-in-prod
      - DJANGO_ALLOWED_HOSTS=*
    volumes:
      - django_data:/app/db_volume

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: adwise_frontend
    ports:
      - "7000:7000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - PORT=7000
    depends_on:
      - backend

volumes:
  django_data:
